baseURL = "/"
languageCode = "en-us"
title = "Dušan Stanković"
theme = "minimal"
googleAnalytics = "UA-38470685-1"

[params]
    author = "Dušan"
    description = "Software engineer, code for fun and profit."
    githubUsername = "dstankovic"
    accent = "#303F9F"
    showBorder = true
    backgroundColor = "white"
    font = "Lato" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "javascript"]
    css = ["/css/styles.css"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/blog/"
    name = "Blog"
    weight = 3

[[menu.main]]
    url = "/talks/"
    name = "Talks/Workshops"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:me@dulerock.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/dulerock/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/dulerock/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://facebook.com/stankovicdushan/"
    name = "facebook"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/dstankovic/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "/public/dusan_stankovic_2018.pdf"
    name = "file"
    weight = 5
